services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fastapiroot
      MYSQL_DATABASE: fastapidb
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db
  
  backend_app:
    container_name: backend_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - db
    volumes:
      - .:/usr/src/app/backend/app/
    
volumes:
  db_volume:
    driver: local